### ISSUE TITLE
QUESTION: Translation from German PHB

### ISSUE THREAD

**Issue by elbracht** [League-of-Foundry-Developers/foundryvtt-dnd5e-lang-de#11]
Is it possible to simply use the translations from the German PHB or are there copyright problems?

**Comment by Fallayn** [comment]
Unfortunately, this isn't possible as the translations are copyrighted property of Ulisses Games / GF9 / WotC.

We *could* contact them to ask, but seeing as Ulisses doesn't even seem to have permission to offer their own translations as digital content, and that the semi-official DND Beyond still doesn't have translated german content, I don't have much hope.

So yeah, we have to do any translations from scratch using the available licensed SRD content.

**Comment by stillday** [comment]
When you have interesst to help by the translation, you can contact me under discord: crash#7509
