### ISSUE TITLE
Error on editing charactersheet

### ISSUE THREAD

**Issue by vascoalexander** [League-of-Foundry-Developers/foundryvtt-dnd5e-lang-de#21]
I get the following error message everytime something is changed on the character sheet:

![2021-08-20 08_59_32-Window](https://user-images.githubusercontent.com/5656715/130194310-f1455562-7bc2-46c6-8bff-7b1915c373e8.png)

The characters were created prior to installing the module. The Error appeared after i deleted the original characterclasses and added the german ones. When i change the name of the classes back to the english version, no error is shown.

foundry version 0.88

**Comment by Fallayn** [comment]
Unfortunately, the root issue needs to be fixed upstream (see https://gitlab.com/foundrynet/dnd5e/-/issues/530 / https://gitlab.com/foundrynet/dnd5e/-/issues/759).

We'll try to find a workaround until then. Thanks for the report!

**Comment by Fallayn** [comment]
FYI, this problem should be solved by new D&D 5E system version 1.6.1, as classes can now be referenced by newly introduced IDs.
I'll need to check and confirm this.

**Comment by 346184** [comment]
This should be fixed in the current version.
