### ISSUE TITLE
Some spell titles are not translated

### ISSUE THREAD

**Issue by elbracht** [League-of-Foundry-Developers/foundryvtt-dnd5e-lang-de#27]
I have found two spells whose titles are not translated. The translation for the following spells is present in dnd5e.spells.json, but is not displayed in Foundry:

- Acid Arrow (Säurepfeil)
- Black Tentacles (Schwarze Tentakel)

![image](https://user-images.githubusercontent.com/2912000/133146035-0d74a774-8796-4988-89eb-6409d0581cdf.png)

I noticed the bug with the following versions
- Foundry v0.8.9
- Babele 2.0.6
- German Translation 1.3

**Comment by Fallayn** [comment]
Sollte in 1.4.0 durch https://github.com/League-of-Foundry-Developers/foundryvtt-dnd5e-lang-de/commit/87de9cc244818cc4748e06ac11760e1857f60494 behoben sein :)
