### ISSUE TITLE
No page translation for class features

### ISSUE THREAD

**Issue by elbracht** [League-of-Foundry-Developers/foundryvtt-dnd5e-lang-de#29]
The source page for class features is not translated.

For "Arkane Tradition" the page should be "SHB S. 86".

![image](https://user-images.githubusercontent.com/2912000/134028262-5e58fbc6-5900-4d07-9674-2f1153cea7e9.png)

**Comment by 346184** [comment]
Closing, as the module is being moved to a new repository. Thanks for reporting!
