### ISSUE TITLE
TODO: Translate compendium content

### ISSUE THREAD

**Issue by Fallayn** [League-of-Foundry-Developers/foundryvtt-dnd5e-lang-de#4]

**Comment by stillday** [comment]
could you use some help with the transfer?

**Comment by Fallayn** [comment]
Always :) Responded on Discord!

**Comment by Fallayn** [comment]
An initial batch of compendium content is translated as of release 1.0.0, so I'm going to close this now, even if we still need to translate more with further updates :)

https://github.com/League-of-Foundry-Developers/foundryvtt-dnd5e-lang-de/releases/tag/1.0.0
