### ISSUE TITLE
New Release Versions missing on Foundry

### ISSUE THREAD

**Issue by gbruckner** [League-of-Foundry-Developers/foundryvtt-dnd5e-lang-de#43]
Hi,

I just noticed that the most current version of this module is 1.3.0 when directly installing it with the Foundry Module Manager which also states that its not tested for compatibility with the current stable version.

I managed to install the latest release from Github now, but this might lead some people to the idea that this module is no longer maintained as the last update there is over 10 months old.

Link: https://foundryvtt.com/packages/FoundryVTT-dnd5e-DE

**Comment by Fallayn** [comment]
Ah, thanks for the reminder. :)

**Comment by Fallayn** [comment]
Fixed!
