### ISSUE TITLE
error in install link!

### ISSUE THREAD

**Issue by ThoGri75** [League-of-Foundry-Developers/foundryvtt-dnd5e-lang-de#5]

**Comment by ThoGri75** [comment]
when you klick on the  link https://github.com/League-of-Foundry-Developers/foundryvtt-dnd5e-lang-de/releases/latest/download/module.json
this error is shown
{"error":"Not Found"}

**Comment by Fallayn** [comment]
The CI pipeline failed a bit there, was fixed - let me know if it crops up again!
